version: '3.8'

networks:
  botnet:

volumes:
  server-data: 
    driver: local

services:
  bot-server:
    image: ghcr.io/bots-house/docker-telegram-bot-api:latest
    environment: 
      # get this values from https://core.telegram.org/api/obtaining_api_id
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    command: 
      # set working directory for files 
      - --dir=/var/lib/telegram-bot-api
      - --verbosity=2
      - --local
    volumes: 
      - server-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
  
  nginx:
    restart: always
    build:
        context: ./web-service/nginx
    container_name: "nginx-server"
    volumes:
      - ./bot:/var/www
    ports:
        - "80:80"
    networks:
      - botnet
    depends_on:
      - php

  redis:
    build:
      context: ./database/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis/redis-data:/var/lib/redis
      - ./database/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - botnet

  php:
    build: 
      context: ./web-service/php
    container_name: "php"
    # Attach
    tty: true
    volumes:
      - ./bot:/var/www
    networks:
      - botnet